from ssz_typing import Bytes1, Bytes4
from spec_typing import (Gwei, Epoch, Slot, DomainType)

FAR_FUTURE_EPOCH = Epoch(2**64 - 1)
BASE_REWARDS_PER_EPOCH = 4
DEPOSIT_CONTRACT_TREE_DEPTH = 2**5
SECONDS_PER_DAY = 86400
JUSTIFICATION_BITS_LENGTH = 4
ENDIANNESS = 'little'

MAX_COMMITTEES_PER_SLOT = 64
TARGET_COMMITTEE_SIZE = 2**7
MAX_VALIDATORS_PER_COMMITTEE = 2**11
MIN_PER_EPOCH_CHURN_LIMIT = 2**2
CHURN_LIMIT_QUOTIENT = 2**16
SHUFFLE_ROUND_COUNT	= 90
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT = 2**16
MIN_GENESIS_TIME = 1578009600

MIN_DEPOSIT_AMOUNT = Gwei(2**0 * 10**9)
MAX_EFFECTIVE_BALANCE = Gwei(2**5 * 10**9)
EJECTION_BALANCE = Gwei(2**4 * 10**9)
EFFECTIVE_BALANCE_INCREMENT	= Gwei(2**0 * 10**9)

GENESIS_SLOT = Slot(0)
GENESIS_EPOCH = Epoch(0)
BLS_WITHDRAWAL_PREFIX = Bytes1(b'\x00')

SECONDS_PER_SLOT = 12
MIN_ATTESTATION_INCLUSION_DELAY = 2**0
SLOTS_PER_EPOCH = 2**5
MIN_SEED_LOOKAHEAD = 2**0
MAX_SEED_LOOKAHEAD = 2**2
SLOTS_PER_ETH1_VOTING_PERIOD = 2**10
SLOTS_PER_HISTORICAL_ROOT = 2**13
MIN_VALIDATOR_WITHDRAWABILITY_DELAY = 2**8
PERSISTENT_COMMITTEE_PERIOD = 2**11
MIN_EPOCHS_TO_INACTIVITY_PENALTY = 4

EPOCHS_PER_HISTORICAL_VECTOR = 2**16
EPOCHS_PER_SLASHINGS_VECTOR = 2**13
HISTORICAL_ROOTS_LIMIT = 2**24
VALIDATOR_REGISTRY_LIMIT = 2**40

BASE_REWARD_FACTOR = 64
WHISTLEBLOWER_REWARD_QUOTIENT = 2**9
PROPOSER_REWARD_QUOTIENT = 8
INACTIVITY_PENALTY_QUOTIENT = 2**25
MIN_SLASHING_PENALTY_QUOTIENT = 2**5

MAX_PROPOSER_SLASHINGS = 2**4
MAX_ATTESTER_SLASHINGS = 2**0
MAX_ATTESTATIONS = 2**7
MAX_DEPOSITS = 2**4
MAX_VOLUNTARY_EXITS = 2**4

DOMAIN_BEACON_PROPOSER = DomainType(int(0).to_bytes(length=4, byteorder='little'))
DOMAIN_BEACON_ATTESTER = DomainType(int(1).to_bytes(length=4, byteorder='little'))
DOMAIN_RANDAO = DomainType(int(2).to_bytes(length=4, byteorder='little'))
DOMAIN_DEPOSIT = DomainType(int(3).to_bytes(length=4, byteorder='little'))
DOMAIN_VOLUNTARY_EXIT = DomainType(int(4).to_bytes(length=4, byteorder='little'))
